import os

API_KEY = os.environ.get('ALPHAVANTAGE_API_KEY')
CLOUFLARE_BUCKET_NAME = os.environ.get('CLOUDFLARE_BUCKET_NAME')
CLOUDFARE_API_URL = os.environ.get('CLOUDFARE_API_URL')
CLOUDFARE_TOKEN_VALUE = os.environ.get('CLOUDFARE_TOKEN_VALUE')
CLOUDFARE_ACCESS_KEY_ID = os.environ.get('CLOUDFARE_ACCESS_KEY_ID')
CLOUDFARE_SECRET_ACCESS_KEY = os.environ.get('CLOUDFARE_SECRET_ACCESS_KEY')
REGION_NAME = os.environ.get('REGION_NAME')

symbol_tickers = ['INTC', 'NVDA', 'AAPL', 'GOOGL', 'AMZN', 'MSFT', 'IBM', 'TSLA', 'FB', 'NFLX']